"""empty message

Revision ID: 02aa3898e4fb
Revises: 8505c2559825
Create Date: 2023-09-07 19:09:46.609445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02aa3898e4fb'
down_revision = '8505c2559825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
